/**
 * Item.js
 *
 * Mongoose model for FOUND items logged into the lost-and-found system. This is
 * the richest, fully-declared (strict) model in the app: it defines an explicit
 * schema for every field plus an embedded sub-schema for claimant ratings.
 *
 * Two schemas are defined:
 *  - ratingSchema: an embedded sub-document capturing a claimant's post-return
 *    star rating/review of the pickup experience.
 *  - itemSchema:   the main found-item document.
 *
 * The model is exported as "Item" and uses Mongoose's default "items"
 * collection. `timestamps: true` auto-manages createdAt/updatedAt.
 */
const mongoose = require("mongoose");

// Generates the application-level external id for a found item, e.g.
// "found_<24-char hex ObjectId>". Used as the default value of itemSchema.id so
// every item has a stable, human-recognizable "found_..." identifier.
function createExternalId() {
  return `found_${new mongoose.Types.ObjectId().toString()}`;
}

// Embedded sub-schema for a single claimant rating/review left after an item is
// returned. Stored inside an Item's `ratings` array (see itemSchema.ratings).
const ratingSchema = new mongoose.Schema(
  {
    // External id of the claim this rating is associated with. Optional.
    claimId: {
      type: String,
      default: "",
      trim: true,
    },
    // Star score from 1 to 5. Required (a rating must have a numeric value).
    rating: {
      type: Number,
      min: 1,
      max: 5,
      required: true,
    },
    // Free-text review left by the claimant. Optional.
    review: {
      type: String,
      default: "",
      trim: true,
    },
    // Name of the claimant who left the review. Optional.
    claimantName: {
      type: String,
      default: "",
      trim: true,
    },
    // Email of the reviewer (claimant). Optional.
    reviewerEmail: {
      type: String,
      default: "",
      trim: true,
    },
    // Moderation state of the review (e.g. "pending" / "approved"). Defaults to "pending".
    status: {
      type: String,
      default: "pending",
      trim: true,
    },
    // When the review was submitted. Defaults to the current time.
    submittedAt: {
      type: Date,
      default: Date.now,
    },
    // When the review was moderated/reviewed. Null until reviewed.
    reviewedAt: {
      type: Date,
      default: null,
    },
  },
  {
    // Do not generate a separate _id for each embedded rating sub-document.
    _id: false,
  }
);

// Main schema for a found item record.
const itemSchema = new mongoose.Schema(
  {
    // Application-level external id (e.g. "found_..."); auto-generated by
    // createExternalId when not supplied. Indexed and trimmed.
    id: {
      type: String,
      default: createExternalId,
      index: true,
      trim: true,
    },
    // Short human-readable title of the item. Required.
    title: {
      type: String,
      required: true,
      trim: true,
    },
    // Longer free-text description of the item. Required.
    description: {
      type: String,
      required: true,
      trim: true,
    },
    // Top-level category (e.g. "electronics", "clothing"). Optional.
    category: {
      type: String,
      default: "",
      trim: true,
    },
    // More specific sub-category (e.g. "Earbuds", "Backpack"). Optional.
    subcategory: {
      type: String,
      default: "",
      trim: true,
    },
    // Primary color of the item. Optional.
    color: {
      type: String,
      default: "",
      trim: true,
    },
    // Brand/manufacturer of the item. Optional.
    brand: {
      type: String,
      default: "",
      trim: true,
    },
    // Where on campus the item was found. Optional.
    locationFound: {
      type: String,
      default: "",
      trim: true,
    },
    // Date the item was found, stored as a string (e.g. "2026-03-11"). Optional.
    dateFound: {
      type: String,
      default: "",
      trim: true,
    },
    // Time of day the item was found, stored as a string (e.g. "12:15"). Optional.
    timeFound: {
      type: String,
      default: "",
      trim: true,
    },
    // Primary display image URL for the item. Optional.
    imageUrl: {
      type: String,
      default: "",
      trim: true,
    },
    // Array of additional photo URLs. Defaults to an empty array.
    photoUrls: {
      type: [String],
      default: [],
    },
    // Physical storage location where the item is being held. Optional.
    storageLocation: {
      type: String,
      default: "",
      trim: true,
    },
    // Condition of the item (e.g. "good", "fair", "excellent"). Optional.
    condition: {
      type: String,
      default: "",
      trim: true,
    },
    // Notable identifying marks/features used to verify ownership. Optional.
    distinguishingFeatures: {
      type: String,
      default: "",
      trim: true,
    },
    // Name of the person who found and turned in the item. Optional.
    finderName: {
      type: String,
      default: "",
      trim: true,
    },
    // Email of the finder. Optional.
    finderEmail: {
      type: String,
      default: "",
      trim: true,
    },
    // Role of the finder (e.g. "staff", "student"). Optional.
    finderRole: {
      type: String,
      default: "",
      trim: true,
    },
    // AI-generated description of the item (e.g. from image analysis). Optional.
    aiDescription: {
      type: String,
      default: "",
      trim: true,
    },
    // Search/keyword tags for matching and filtering. Defaults to empty array.
    tags: {
      type: [String],
      default: [],
    },
    // Workflow status (e.g. "pending_review", "approved", "claimed", "returned").
    // Defaults to "pending_review" for newly logged items.
    status: {
      type: String,
      default: "pending_review",
      trim: true,
    },
    // Type discriminator; defaults to "found" (this model holds found items).
    itemType: {
      type: String,
      default: "found",
      trim: true,
    },
    // Handling priority (e.g. "low", "medium", "high", "critical"). Optional.
    priority: {
      type: String,
      default: "",
      trim: true,
    },
    // Internal tracking code/label for the physical item (e.g. "FB-2026-HF82"). Optional.
    itemCode: {
      type: String,
      default: "",
      trim: true,
    },
    // Office/staff group the item is assigned to for handling. Optional.
    assignedTo: {
      type: String,
      default: "",
      trim: true,
    },
    // Whether the item has been flagged for special attention. Defaults to false.
    isFlagged: {
      type: Boolean,
      default: false,
    },
    // External id of a LostReport this found item has been linked/matched to. Optional.
    linkedLostReportId: {
      type: String,
      default: "",
      trim: true,
    },
    // Whether a claim/return has been confirmed for this item. Defaults to false.
    claimConfirmed: {
      type: Boolean,
      default: false,
    },
    // Timestamp when the claim was confirmed. Null until confirmed.
    claimConfirmedAt: {
      type: Date,
      default: null,
    },
    // Embedded list of claimant ratings/reviews (see ratingSchema). Defaults to empty.
    ratings: {
      type: [ratingSchema],
      default: [],
    },
  },
  {
    // Auto-manage createdAt / updatedAt timestamp fields on each item.
    timestamps: true,
  }
);

// Export the compiled "Item" model, reusing an existing one if already compiled
// (prevents OverwriteModelError on repeated requires / hot reloads).
module.exports = mongoose.models.Item || mongoose.model("Item", itemSchema);
